pixijs/assetpack

- .github/workflows/release.yml
- packages/manifest/README.md
- packages/manifest/src/pixi.ts
- packages/manifest/test/Manifest.test.ts
- packages/webfont/test/Webfont.test.ts
BREAKING CHANGE: renames `name` and `srcs` to `alias` and `src` for compatibility with pixi v8 which removed these options
> feat(manifest): update manifest output for v8 manifest compatibility

- packages/assetpack/src/pixi/index.ts
this code 
```
apConfig.resolutions ??= config?.resolutions;
```
always results in the merged value instead of the config value.
> fix: pixiPipes resolution options override 

- packages/assetpack/src/image/compress.ts
- packages/assetpack/test/image/Compress.test.ts
alternative to #73
the compress plugin should copy over the original image if png/jpg is set to false, otherwise the image is lost
> fix: compress plugin not outputting original image

- packages/docs/docs/guide/pipes/texture-packer.mdx
In [Texture Packer Compress](https://pixijs.io/assetpack/docs/guide/pipes/texture-packer/#texture-packer-compress) document, there's a typo in the code. It should be:
`import { texturePackerCompress } from "@assetpack/core/texture-packer";`
> chore: fix typo in Texture Packer Compress

- package-lock.json
- packages/assetpack/package.json
- packages/assetpack/src/image/compress.ts
- packages/assetpack/src/image/utils/compressGpuTextures.ts
- packages/assetpack/src/image/utils/compressSharp.ts
- packages/assetpack/src/spine/AtlasView.ts
- packages/assetpack/src/spine/spineAtlasCompress.ts
- packages/assetpack/src/texture-packer/texturePackerCompress.ts
- packages/assetpack/test/image/Compress.test.ts
- packages/assetpack/test/manifest/Manifest.test.ts
- packages/assetpack/test/spine/spineAtlasAll.test.ts
- packages/assetpack/test/spine/spineAtlasCompress.test.ts
- packages/assetpack/test/texture-packer/texturePackerAll.test.ts
- packages/assetpack/test/texture-packer/texturePackerCompress.test.ts
- packages/assetpack/test/texture-packer/texturePackerManifest.test.ts
- packages/assetpack/vitest.config.js
- packages/docs/docs/guide/pipes/compress.mdx
- packages/docs/docs/guide/pipes/spine.mdx
- packages/docs/docs/guide/pipes/texture-packer.mdx
The image compression extension has been enhanced with the ability to generate `ASTC`, `BC7`, and supercompressed `Basis` textures.
> feat: Add compressed textures support

- packages/assetpack/src/core/Asset.ts
- packages/assetpack/src/core/pipes/AssetPipe.ts
- packages/assetpack/src/core/pipes/PipeSystem.ts
- packages/assetpack/src/image/compress.ts
- packages/assetpack/src/image/utils/compressGpuTextures.ts
- packages/assetpack/src/manifest/pixiManifest.ts
- packages/assetpack/src/webfont/sdf.ts
- packages/assetpack/src/webfont/webfont.ts
- packages/assetpack/test/manifest/Manifest.test.ts
- packages/assetpack/test/spine/spineAtlasAll.test.ts
- packages/assetpack/test/spine/spineAtlasManifest.test.ts
- packages/assetpack/test/texture-packer/texturePackerAll.test.ts
- packages/assetpack/test/texture-packer/texturePackerCompress.test.ts
- packages/assetpack/test/texture-packer/texturePackerManifest.test.ts
- packages/assetpack/test/webfont/Webfont.test.ts
- packages/assetpack/vitest.config.js
- packages/docs/docs/guide/pipes/overview.mdx
- packages/docs/docs/guide/pipes/webfont.mdx
This PR allows tags that are not defined by assetpack to be added to the manifest data object directly, instead of being under the tags section.
I've added the `legacyMetaData` option to the manifest plugin which will still add these custom tags to the `tags` section in the manifest for backwards compatibility.
This PR also fixes the issue with fonts not working with cache busting it adds the `family` tag and then pixi is able to read this directly
> feat: allow tags to be added manifest data directly

- package-lock.json
- packages/assetpack/package.json
Bump `gpu-tex-enc` to version 1.2.5, where the `cpu-features` library is made optional.
> fix: Bump gpu-tex-enc to 1.2.5

- packages/assetpack/src/manifest/pixiManifest.ts
- packages/assetpack/test/manifest/Manifest.test.ts
- packages/docs/docs/guide/pipes/manifest.mdx
This PR takes care of bundle name conflicts by adding support of `nameStyle` property.
Unlike v0.x.x which used complex regex to extract relative name from path, this PR traverses asset tree and generates the relative name without much effort.
Fixes/Closes #87
> feat: Added support for nameStyle option in Manifest

- packages/docs/docs/guide/getting-started/pixi.md
Remove the extra brackets, which is an invalid JSON format.
For example, it should be:
```
pixiPipes({
texturePacker: { texturePacker: { nameStyle: 'short' }},
}),
```
Instead of :
```
pixiPipes({
texturePacker: {{ texturePacker: { nameStyle: 'short' }}},
}),
```
P.S. I found having two `texturePacker` keys confusing and couldn't get it to work with just one on the first try.
> fix: pixi.md docs

- packages/assetpack/src/core/AssetWatcher.ts
Ran into #93 where the watch command doesn't work. Converting the paths to unix style ones appears to fix the issue for windows.
Not sure if this is the right way to fix it or not and I'm not able to test this on macOS.
> fix: Use unix paths in AssetWatcher.ts

- packages/assetpack/src/cli/index.ts
closes #107
Newer versions of node no longer throw `ERR_REQUIRE_ESM` when using `require` on a esm file, we now check to see if `__esModule` is defined instead
> fix: node 22 support

- packages/assetpack/src/image/mipmap.ts
- packages/assetpack/test/image/Mipmap.test.ts
Hi
Sorry that I am coming without an issue but I think PR is pretty simple so we can start discussion here.
I need to generate fixed resolution other then 1. After migration to assetpack 1.2 (after 0.8) I found out that `fix` tag will not change asset resolution (size) but only naming.
I mean configs like
```
resolutions: {
low: 0.5,
default: 1,
},
fixedResolution: 'low'
```
with `fix` tag on asset will copy asset as is without name or size changing.
I can reach needed result with config mentioned before but without `fix` tag applied but then redundant unchanged asset appear as output for default option. 
You can reproduce it with [this](https://github.com/pixijs/assetpack/blob/f293a154cbef42938f965e5e86505d7181bb78da/packages/assetpack/test/image/Mipmap.test.ts#L70) test by adding `fix` …
> fix: apply mipmap fixed resolution accordingly to fixed and largest resolutions

- packages/assetpack/src/texture-packer/packer/fitTextureToPacker.ts
- packages/assetpack/test/texture-packer/texturePacker.test.ts
Since setting power of two is never used anywhere, I add logic check and process power of two for texture size.
> fix: packed asset never power of two

- packages/assetpack/src/core/Asset.ts
- packages/assetpack/src/core/AssetCache.ts
- packages/assetpack/src/core/AssetPack.ts
- packages/assetpack/src/core/AssetWatcher.ts
- packages/assetpack/src/core/logger/Logger.ts
- packages/assetpack/src/core/utils/syncAssetsWithCache.ts
- packages/assetpack/test/core/AssetWatcher.test.ts
- packages/assetpack/test/core/Assetpack.test.ts
Added some stats and a few other bits!
1. add stats object to assets
- All assets not have a little stat object that stores transformation information. Currently this is transform time, transform date, success and error (if success is false).
2. expose root asset
- Added a `rootAsset` to `AssetPack` so devs who are feeling adventurous can gain access to the underlying assets
3. tweak how we use the cache
- Whilst writing the test, i realised that when calling `run` on the same assetpack instance multiple times and in between runs, changing the assets in the input folder then things get broken! 
- The main reason for this was that the cache was written correctly between runs, but only read on the first run. I have adjusted the API so that now `AssetWatcher` now expects an `AssetCache` …
> feat: add stat object that stores transformation information 

- packages/assetpack/src/core/Asset.ts
- packages/assetpack/src/spine/spineAtlasCacheBuster.ts
- packages/assetpack/src/texture-packer/texturePackerCacheBuster.ts
When watching assets, occasianally one is deleted and we then try to read its hash the item does not exist and an error is thrown.
This PR adds a try catch around this issue. This won't cause any further issues as the asset without the file will have been flagged for deletion anyways.
> fix: deleting asset causing crash when watching assets

- packages/assetpack/src/texture-packer/texturePackerCacheBuster.ts
- packages/assetpack/test/texture-packer/texturePackerCacheBuster.test.ts
**TPS** Compatible with files with the same name in different directories.
> fix: Errors resulting from identical TPS file names in different dir

- packages/assetpack/src/core/AssetPack.ts
- packages/assetpack/test/core/Assetpack.test.ts
- adds an onComplete callback option to watch. This is called each time assetpack has finished updating assets
- fix watch promise resolve to happen at the right time
- add test
> feat: add onComplete to watch

- packages/assetpack/src/image/mipmap.ts
- packages/assetpack/src/spine/spineAtlasMipmap.ts
- packages/assetpack/src/texture-packer/texturePacker.ts
- packages/assetpack/src/webfont/sdf.ts
- packages/assetpack/test/core/AssetWatcher.test.ts
- packages/assetpack/test/image/Mipmap.test.ts
- packages/assetpack/test/spine/spineAtlasMipmap.test.ts
- packages/assetpack/test/texture-packer/texturePacker.test.ts
- packages/assetpack/test/webfont/Webfont.test.ts
- packages/assetpack/vitest.config.js
- packages/docs/docs/guide/pipes/mipmap.mdx
- packages/docs/docs/guide/pipes/spine.mdx
- packages/docs/docs/guide/pipes/texture-packer.mdx
This PR adds the `nomip` tag which can be placed on folders/images that you do not want any mipmaps being generated for. This is useful for things like bitmap fonts where we currently don't have any plugins to resize these
This has become necessary since #96 as we now correctly apply the `fix` tag for the mipmap plugin. Before this change the `fix` tag incorrectly acted like the `nomip` tag. So now we have an explicit option for this
fixes: #113
> feat: add nomip tag to avoid mipmaps being generated

- packages/docs/docs/guide/pipes/webfont.mdx
Fix a misspelling in the documentation: the exported function names in the webfont plugin should be `sdfFont / msdfFont`.
> fix: sdf/msdf function names in doc

- packages/assetpack/src/manifest/pixiManifest.ts
- packages/assetpack/test/manifest/Manifest.test.ts
- packages/docs/docs/guide/pipes/manifest.mdx
Added options to control the sort of the src array. Using these options you can control the loading order of asset JSON files.
This can solve the problem of not loading all the relevant asset files when using multipack generated by texture-packer. PIXI seems to only read the first `src` entry per asset. By default the assets are sorted lexically in descending order. This presents an issue with multi packs since related multi packs are only defined in the first JSON file.
If the JSON with related multi packs is in the first position of the `src` array all assets are loaded as expected.
```JavaScript
...
pixiManifest({
...
srcSortOptions: {
numeric: true,
order: "ascending",
}
}),
...
```
> feat: pixiManifest: Src sorting options
